# Generated by Django 4.2.5 on 2023-10-13 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
    ]
